--- 
clone: 
  depth: 1
kind: pipeline
name: Kyaru-AOSP
concurrency:
  limit: 6
steps: 
  - 
    commands: 
      - git config --global user.name Egii
      - git config --global user.email regidesoftian@gmail.com
      - git clone --depth=1 https://github.com/KuroSeinenbutV2/Quantum-Kyaru-Sweet kernel
      - "cp build.sh kernel && cd kernel"
      - "bash build.sh"
    environment: 
      TG_TOKEN:
        from_secret: TG_TOKEN
      TG_CHAT_ID:
        from_secret: TG_CHAT_ID
      VARIANT: AOSP
    image: fajar4561/saciku:latest
    name: Kyaru-Build
    trigger: 
      branch: 
        - sweet

--- 
clone: 
  depth: 1
kind: pipeline
name: Kyaru-MIUI
concurrency:
  limit: 6
steps: 
  - 
    commands: 
      - git config --global user.name Egii
      - git config --global user.email regidesoftian@gmail.com
      - git clone --depth=1 https://github.com/KuroSeinenbutV2/Quantum-Kyaru-Sweet -b Miui  kernel
      - "cp build.sh kernel && cd kernel"
      - "bash build.sh"
    environment: 
      TG_TOKEN:
        from_secret: TG_TOKEN
      TG_CHAT_ID:
        from_secret: TG_CHAT_ID
      VARIANT: MIUI
    image: fajar4561/saciku:latest
    name: Kyaru-Build
    trigger: 
      branch: 
        - sweet
