kind: pipeline
name : AOSP Clang Mirror
version: rev1.5_template
steps:
 - name: LLVM-tc Compilation
   image: xyzuan/xdocker:latest
   environment:
     CLANG_VERSION:
       from_secret: CLANG_VERSION
     GH_USERNAME:
       from_secret: GH_USERNAME
     GH_EMAIL:
       from_secret: GH_EMAIL
     GH_TOKEN:
       from_secret: GH_TOKEN
     GH_PUSH_REPO_URL:
       from_secret: GH_PUSH_REPO_URL
   commands:
     - bash mirror.sh