--- 
clone: 
  depth: 1
kind: pipeline
name: Leafaa-AOSP
concurrency:
  limit: 6
steps: 
  - 
    commands: 
      - cp -af sources.list /etc/apt/
      - cp -af 99own /etc/apt/apt.conf.d/
      - apt-get autoremove -y && apt-get --purge remove -y && apt-get autoclean -y && apt-get update -y && apt-get upgrade -y && apt-get dist-upgrade -y
      - dpkg-reconfigure -a && dpkg --configure -a
      - ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
      - apt-get -y install -f cpio gcc llvm lld g++-multilib python2 clang git libxml2 python3-pip gcc llvm lld g++-multilib clang default-jre git automake lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng bc libstdc++6 libncurses5 wget python3 python3-pip gcc clang libssl-dev rsync flex git-lfs libz3-dev libz3-4 axel tar bc binutils-dev bison build-essential ca-certificates ccache clang cmake curl file flex git libelf-dev libssl-dev lld make ninja-build python3-dev texinfo u-boot-tools xz-utils zlib1g-dev && python3 -m pip install networkx && pip3 install --upgrade gupload
      - "git config --global user.name Egii"
      - "git config --global user.email regidesoftian@gmail.com"
      - "git clone --depth=1 https://github.com/filolia/android_kernel_xiaomi_mt6768 -b twelve kernel"
      - "cp build.sh kernel"
      - "bash build.sh FullLTO"
    environment: 
      BOT_TOKEN:
        from_secret: BOT_TOKEN
      TG_CHAT_ID:
        from_secret: TG_CHAT_ID
      VARIANT: AOSP
    image: ubuntu:jammy-20211029
    name: Leafaa-Build
    trigger: 
      branch: 
        - leafa

--- 
clone: 
  depth: 1
kind: pipeline
name: Leafaa-MIUI
concurrency:
  limit: 6
steps: 
  - 
    commands: 
      - cp -af sources.list /etc/apt/
      - cp -af 99own /etc/apt/apt.conf.d/
      - apt-get autoremove -y && apt-get --purge remove -y && apt-get autoclean -y && apt-get update -y && apt-get upgrade -y && apt-get dist-upgrade -y
      - dpkg-reconfigure -a && dpkg --configure -a
      - ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
      - apt-get -y install -f cpio gcc llvm lld g++-multilib python2 clang git libxml2 python3-pip gcc llvm lld g++-multilib clang default-jre git automake lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng bc libstdc++6 libncurses5 wget python3 python3-pip gcc clang libssl-dev rsync flex git-lfs libz3-dev libz3-4 axel tar bc binutils-dev bison build-essential ca-certificates ccache clang cmake curl file flex git libelf-dev libssl-dev lld make ninja-build python3-dev texinfo u-boot-tools xz-utils zlib1g-dev && python3 -m pip install networkx && pip3 install --upgrade gupload
      - "git config --global user.name Egii"
      - "git config --global user.email regidesoftian@gmail.com"
      - "git clone --depth=1 https://github.com/filolia/android_kernel_xiaomi_mt6768 -b twelve-miui kernel"
      - "cp build.sh kernel"
      - "bash build.sh ThinLTO"
    environment: 
      BOT_TOKEN:
        from_secret: BOT_TOKEN
      TG_CHAT_ID:
        from_secret: TG_CHAT_ID
      VARIANT: MIUI
    image: ubuntu:jammy-20211029
    name: Leafaa-Build
    trigger: 
      branch: 
        - leafa