--- 
clone: 
  depth: 1
kind: pipeline
name: TWRP-Builder
concurrency:
  limit: 6
steps: 
  - 
    commands: 
      - "bash build.sh"
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
      TG_TOKEN:
        from_secret: TG_TOKEN
      TG_CHAT_ID:
        from_secret: TG_CHAT_ID
    image: fajar4561/saciku:latest
    name: Build
    trigger: 
      branch: 
        - unified-tes
