---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: Start syncing && Compiling
  image: brock5555/recovery
  environment:
       GH_TOKEN:
         from_secret: GH_TOKEN
       TG_CHAT_ID:
         from_secret: TG_CHAT_ID
       TG_TOKEN:
         from_secret: TG_TOKEN
  commands:
  - bash build.sh
