--- 
clone: 
  depth: 1
kind: pipeline
name: Yukina-Selene
concurrency:
  limit: 6
steps: 
  - 
    commands:
      - git config --global user.name Egii
      - git config --global user.email regidesoftian@gmail.com
      - git clone --depth=1 https://github.com/Himemoria/android_kernel_xiaomi_selene kernel
      - "cp build.sh kernel && cd kernel"
      - "bash build.sh"
    environment: 
      TG_TOKEN:
        from_secret: TG_TOKEN
      TG_CHAT_ID:
        from_secret: TG_CHAT_ID
    image: fajar4561/saciku:latest
    name: Yukina-Build
    trigger: 
      branch: 
        - roulette
